 vl_compilenn('enableGpu', true, 'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0', ...
               'cudaMethod', 'nvcc', ... ...
               'enableCudnn', true, 'cudnnRoot', 'C:\Users\Jesse Marshall\Documents\GitHub\Movement_analysis\Common\matconvnet-1.0-beta23\matconvnet-1.0-beta23\local\cuda') ;
% %            
%             vl_compilenn('enableGpu', true, 'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0', ...
%                'cudaMethod', 'nvcc') ;